includes("../../xmake.utils.lua")

target("panel")
    set_extension("panel")
    add_files("*.cpp", "*.cppm")
    add_files("../theme/color.cppm")
    add_files("../theme/quantize.cppm")
    add_files("../theme/generate.cppm")
    add_files(path.join(os.projectdir(), "libs/material-colors/*.cppm"))
    add_packages("libpipewire-0.3")
